### ISSUE TITLE
Alias MultiViews on Ubuntu 14.04

### ISSUE THREAD

**Issue by rgormley** [dev-sec/chef-apache-hardening#14]
Default recipe causes a config error on Ubuntu 14.04:

```
AH00526: Syntax error on line 18 of /etc/apache2/mods-enabled/alias.conf:
Either all Options must start with + or -, or no Option may.
```

Changing "`MultiViews`" to "`+MultiViews`" (or "`-MultiViews`", for that matter) in `/etc/apache2/mods-enabled/alias.conf` resolves the issue.

**Comment by chris-rock** [comment]
thanks @rgormley As far as I understood the issue, the problem is located here: https://github.com/svanzoest/apache2-cookbook/blob/cd03a52e1e937889ce510e2aff492642a0b8ba3f/templates/default/mods/alias.conf.erb
Am I right?

**Comment by cmjosh** [comment]
This is the template/line that's causing the problem on apache2.4 installs:
https://github.com/hardening-io/chef-apache-hardening/blob/master/templates/default/mods/alias.conf.erb#L18

**Comment by chris-rock** [comment]
Thanks @cmjosh we definitely need a plus there. Would you like to create a PR? Maybe we should also use attributes for this config.

**Comment by vikramgorla** [comment]
:+1:
